export function getTagSymbol(tag: string): string {
  const tagSymbols: { [key: string]: string } = {
    'vegetarian': '🥬',
    'vegan': '🌱',
    'halal': '☪️',
    'kosher': '✡️',
    'gluten-free': '🚫🌾',
    'dairy-free': '🥛❌',
    'nut-free': '🥜❌',
    'low-carb': '🔢',
    'keto': '🥑',
    'paleo': '🦴',
    'spicy': '🌶️',
    'sweet': '🍯',
    'savory': '🧂',
    'healthy': '💚',
    'comfort-food': '🤗',
    'quick': '⚡',
    'easy': '👌',
    'protein': '💪',
    'high-fiber': '🌾',
    'low-sodium': '🧂❌',
    'organic': '🌿',
    'raw': '🥒',
    'fermented': '🦠',
    'baked': '🥖',
    'grilled': '🔥',
    'fried': '🍳',
    'steamed': '♨️',
    'slow-cooked': '🐌',
    'one-pot': '🍲',
    'meal-prep': '📦',
    'kid-friendly': '👶',
    'diabetic-friendly': '🩺',
    'heart-healthy': '❤️',
    'anti-inflammatory': '🧘',
    'immune-boosting': '🛡️',
    'energy-boosting': '⚡',
    'detox': '🧹',
    'seasonal': '🍂',
    'holiday': '🎄',
    'appetizer': '🥗',
    'main-course': '🍽️',
    'side-dish': '🥄',
    'dessert': '🍰',
    'snack': '🍿',
    'drink': '🥤',
    'soup': '🍜',
    'salad': '🥗',
    'pasta': '🍝',
    'rice': '🍚',
    'bread': '🍞',
    'seafood': '🐟',
    'chicken': '🐔',
    'beef': '🥩',
    'pork': '🐷',
    'lamb': '🐑',
    'turkey': '🦃',
    'fish': '🐠',
    'shellfish': '🦐',
    'eggs': '🥚',
    'cheese': '🧀',
    'chocolate': '🍫',
    'fruit': '🍎',
    'vegetable': '🥕',
    'grain': '🌾',
    'legume': '🫘',
    'nut': '🥜',
    'seed': '🌰',
    'herb': '🌿',
    'spice': '🌟'
  };
  
  return tagSymbols[tag.toLowerCase()] || '🏷️';
}

export function getTagsDisplay(tags: string[]): string {
  if (!tags || tags.length === 0) return '';
  
  return tags.map(tag => getTagSymbol(tag)).join(' ');
}